/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge/index.vue')['default']
    DetailInfo: typeof import('./src/components/DetailInfo/DetailInfo.vue')['default']
    Line: typeof import('./src/components/Line/Line.vue')['default']
    PicViewer: typeof import('./src/components/PicViewer/PicViewer.vue')['default']
    Test: typeof import('./src/components/DetailInfo/test.vue')['default']
    Test1: typeof import('./src/components/PicViewer/test1.vue')['default']
    Test2: typeof import('./src/components/PicViewer/test2.vue')['default']
    Test3: typeof import('./src/components/PicViewer/test3.vue')['default']
    Test4: typeof import('./src/components/PicViewer/test4.vue')['default']
    Test5: typeof import('./src/components/PicViewer/test5.vue')['default']
    Test6: typeof import('./src/components/PicViewer/test6.vue')['default']
    Test7: typeof import('./src/components/PicViewer/test7.vue')['default']
  }
}
